project_id = "hdnoaihwlrwhoifyaspi"

[functions.email-webhook]
verify_jwt = false

[functions.google-drive-folders]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = false

[functions.invite-user]
verify_jwt = true

[functions.auth-email-hook]
verify_jwt = false

[functions.send-daylog-email]
verify_jwt = true
